version: '3.8'
services:
  dev-db:
    container_name: 12-factor-app-dev-db
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432
    networks:
      - 12-factor-app

networks:
  12-factor-app:
