version: '3.8'
services:
  prod-db:
    container_name: 12-factor-app-prod-db
    image: postgres:latest
    env_file:
      - ../prod.env
    ports:
      - '5432:5432'
    networks:
      - 12-factor-app

  prod-api:
    container_name: 12-factor-app-prod-api
    build:
      context: ../
      dockerfile: Dockerfile
    image: grizli418/12-factor-app
    restart: 'on-failure:3'
    env_file:
      - ../prod.env
    ports:
      - '3000:3000'
    depends_on:
      - prod-db
    command: sh -c 'while ! nc -z 12-factor-app-prod-db 5432; do sleep 1; done; npm run migrate:deploy; npm start'
    networks:
      - 12-factor-app

networks:
  12-factor-app:
